apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: prometheus
  labels:
    app: cadvisor
spec:
  selector:
    app: cadvisor
  ports:
  - port: 8080
    name: cadvisor-port
  clusterIP: None
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cadvisor
  namespace: prometheus
  labels:
    app: cadvisor
spec:
  selector:
    matchLabels:
      app: cadvisor
  template:
    metadata:
      labels:
        app: cadvisor
    spec:
      containers:
      - image: google/cadvisor
        imagePullPolicy: IfNotPresent
        name: cadvisor
        ports:
        - name: cadvisor-port
          containerPort: 8080
        volumeMounts:
        - mountPath: /var/run
          name: run-volume
        - mountPath: /sys
          name: sys-volume
        - mountPath: /var/lib/docker
          name: docker-volume
      volumes:
      - name: run-volume
        hostPath:
          path: /var/run
          type: Directory
      - name: sys-volume
        hostPath:
          path: /sys
          type: Directory
      - name: docker-volume
        hostPath:
          path: /var/lib/docker
          type: Directory
