apiVersion: v1
kind: Pod
metadata: 
  name: testcurl
  namespace: prometheus
spec: 
  containers:
  - name: testcurl
    image: curlimages/curl:latest
    command: 
    - sleep
    - "3600"
      
  
