apiVersion: v1
kind: Pod
metadata:
  name: cm-testpod
  namespace: elk
spec:
  containers:
  - name: cm-testpod
    image: busybox
    command:
    - sleep
    - "3600"
    volumeMounts:
    - name: cfg-vol
      mountPath: /var/path1/path2/kibana.yaml
      subPath: path1/path2/kibana.yaml
  volumes:
  - name: cfg-vol
    configMap:
      name: cm-kibana-yaml
      items:
      - key: kibana.yaml
        path: path1/path2/kibana.yaml
      
